config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'gardens#index'

  resources :gardens do
    resources :plants, only: [:create]
  end
  resources :plants, only: [:destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :user
  has_many :plants, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
  URL_REGEXP = %r{\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,9}(:[0-9]{1,5})?(\/.*)?\z}ix
  validates :banner_url, format: { with: URL_REGEXP, message: 'format invalid' }
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  validates :name, presence: true, uniqueness: { scope: :garden_id }
  validates :image_url, presence: true
  URL_REGEXP = %r{\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,9}(:[0-9]{1,5})?(\/.*)?\z}ix
  validates :image_url, format: { with: URL_REGEXP, message: 'format invalid' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :gardens, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @gardens = Garden.all
  end

  def show
    @garden = Garden.find(params[:id])
    @plant = Plant.new
    @plants = @garden.plants
  end

  def new
    @garden = Garden.new
  end

  def create
    @garden = Garden.new(garden_params)
    @garden.user = current_user
    if @garden.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def destroy
    @garden = Garden.find(params[:id])
    @garden.destroy
    redirect_to root_path
  end

  def edit
    @garden = Garden.find(params[:id])
  end

  def update
    @garden = Garden.find(params[:id])
    @garden.update(garden_params)
    if @garden.save
      redirect_to garden_path(@garden)
    else
      render :edit
    end
  end

  private

  def garden_params
    params.require(:garden).permit(:name, :banner_url)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def index
    @gardens = Garden.where(user: current_user)
  end

  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render 'gardens/show'
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @garden = @plant.garden
    @plant.destroy
    redirect_to garden_path(@garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gardens/_plant_card.html.erb
<div class="card-plant" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.image_url %>), url('https://source.unsplash.com/400x300/?flower')">
  <%= plant.name %>
  <% if @garden.user == current_user %>
    <%= (link_to "+", plant_path(plant), method: :delete, data: { confirm: "Are you   sure?" }, class: "card-remove-link") %>
  <% end %>
</div>

app/views/gardens/edit.html.erb
<div class="pt-30 container">
  <h1 class="text-center"><%= @garden.name %></h1>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@garden) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :banner_url %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/gardens/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%= image_path('home_banner.jpg') %>)">
  <div class="container">
    <h1>My Garden Manager</h1>
    <p>Manage, Cultivate and Grow your Garden and your Experience</p>
    <%= link_to "Discover", "#how", class: "btn btn-flat" %>
  </div>
</div>

<div class="container">
  <div class="section">
    <h2 id="how" class="text-center">How does it work?</h2>
    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_garden_path do %>
          <div class="icon">
            <%= image_tag "garden.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Create your garden</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_garden_path do %>
          <div class="icon">
            <%= image_tag "circles.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Add your plants</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_garden_path do %>
          <div class="icon">
            <%= image_tag "watering.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Manage your daily activity</p>
      </div>
    </div>
  </div>
  <div class="section">
    <h2 class="text-center">Our Community Best Gardens</h2>
    <div class="cards">
      <% @gardens.each do |garden| %>
        <%= render "garden_card", garden: garden %>
      <% end %>
    </div>
  </div>
  <div class="section">
    <div class="text-center">
      <%= link_to "Create my garden", new_garden_path, class: "btn btn-flat" %>
    </div>
  </div>
</div>

app/views/gardens/new.html.erb
<div class="pt-30 container">
  <h1 class="text-center">New Garden</h1>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@garden) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :banner_url %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>'), url('https://source.unsplash.com/1200x700/?garden');">
  <% if @garden.user == current_user %>
    <%= link_to "+", garden_path(@garden), method: :delete, data: { confirm: "Are you sure?" }, class: "garden-remove-link" %>
    <%= link_to "Edit", edit_garden_path(@garden), id: "edit-link" %>
  <% end %>
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>
<div class="pt-30 container">
  <div class="cards">
    <% @garden.plants.each do |plant| %>
      <%= render "gardens/plant_card", plant: plant %>
    <% end %>
  </div>
  <% if @garden.user == current_user %>
  <div class="pt-30 row justify-content-center">
    <div class="col-12 col-md-4">
      <h4 class="text-center">Add a plant</h4>
      <%= simple_form_for [ @garden, @plant ] do |f| %>
        <%= f.input :name, placeholder: "Palm tree" %>
        <%= f.input :image_url, placeholder: "https://some_nice_image_found_on_google.jpg" %>
        <div class="form-actions">
          <%= f.submit "Add", class: "btn btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Garden Manager</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('logo.png') %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <!-- Hotjar Tracking Code for https://www.david-haffner.me -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:<%=ENV['HOTJAR_KEY']%>,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render 'shared/flashes' %>
    <%= render "shared/footer" %>
    <!-- WARNING: DO NOT DELETE THE LINE BELOW -->
    <div id="rails-garden-manager-watermark"></div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/plants/_garden_card.html.erb
<%= link_to garden_path(garden) do %>
  <div class="card-garden">
    <%= image_tag garden.banner_url %>
    <div class="card-garden-infos">
      <div>
        <h2><%= garden.name %></h2>
      </div>
    </div>
  </div>
<% end %>

app/views/plants/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%= image_path('home_banner.jpg') %>)">
  <div class="section">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_garden_path do %>
          <div class="icon">
            <%= image_tag "garden.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Create your garden</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to plants_path(anchor: "my_gardens") do %>
          <div class="icon">
            <%= image_tag "circles.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Add your plants</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_garden_path do %>
          <div class="icon">
            <%= image_tag "watering.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Manage your daily activity</p>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="section">
    <h2  id="my_gardens" class="text-center">Your Gardens</h2>
    <div class="cards">
      <% @gardens.each do |garden| %>
        <%= render "garden_card", garden: garden %>
      <% end %>
    </div>
  </div>
  <div class="section">
    <div class="text-center">
      <%= link_to "Create my garden", new_garden_path, class: "btn btn-flat" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
    "Icon made by <a href="https://www.flaticon.com/authors/pixel-perfect">Pixel perfect</a> from <a href="http://www.flaticon.com/">www.flaticon.com"</a>
  </div>
</div>

<%# https://www.flaticon.com/authors/smashicons
    https://www.flaticon.com/authors/ultimatearm
    https://www.freepik.com/?_gl=1*133623p*test_ga*MjExMzQwOTUyNS4xNjMxNjA1OTIz*test_ga_523JXC6VL7*MTYzMTYwNTkyMi4xLjEuMTYzMTYwNjU3OS40OQ..
 %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <% unless user_signed_in? %>
    <%= link_to new_user_session_path, class: "navbar-brand" do %>
      <div class="logo">
        <%= image_tag "farming.svg" %>
      </div>
        <p id="navbar-text">Login</p>
    <% end %>
  <% end %>
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="logo">
      <%= image_tag "circles.svg" %>
    </div>
      <p id="navbar-text">Home</p>
  <% end %>
</div>

app/views/shared/_navbarlewagon.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>